### ISSUE TITLE
Use public data sets for unit tests and benchmarks

### ISSUE THREAD

**Issue by cloderic** [craft-ai/craft-ai-kit-energy#13]
# Objective #

- The kit has a collection of unit tests and benchmark (regarding the quality of the predictive models) working on publicly available dataset working.
- Work on the UCI energy dataset (already cleanly retrieved in https://github.com/craft-ai/craft-ai-kit-energy#data-preparation) and the GEF dataset

# Definition of Done #

- [x] Select a sample of datasets (UCI & AMPds2)
- [x] Execute benchmarks
- [x] Implement a rolling prediction feature in the kit -> #49 
    - name it `evaluate`.
- [x] Implement a ava-based test that computes the week based benchmark for ampds2 & UCI (to be executed on the master branch only)-> #49
- [x] Integrate 3rd party algorithms to the `benchmark` repo (including metaparameters search)

---------

- Potential datasets can be found here:
    - <https://archive.ics.uci.edu/ml/datasets/Individual+household+electric+power+consumption>
    - [Awesome Public Datasets - Energy](https://github.com/caesar0301/awesome-public-datasets#energy)
    - ⭐️ [DRED](http://www.st.ewi.tudelft.nl/~akshay/dred/)
    - ⭐️ [AMPds2](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/FIE0S4&version=1.2)
    - ⭐️ [ECO](http://rossa-prod-ap11.ethz.ch/delivery/DeliveryManagerServlet?dps_pid=IE594964)
  - ⭐️ [GEF](http://blog.drhongtao.com/2017/03/gefcom2014-load-forecasting-data.html)

**Comment by PierreSalaun** [comment]
idea of dataset:
http://data.ukedc.rl.ac.uk/simplebrowse/edc/efficiency/residential/EnergyConsumption/Domestic/UK-DALE-2015

**Comment by PierreSalaun** [comment]
Commercial Building Energy Dataset:
http://combed.github.io/

**Comment by PierreSalaun** [comment]
Needs to give a valid email, might be worth it:
http://redd.csail.mit.edu/

**Comment by rmdh** [comment]
Tom worked on ECO

**Comment by cloderic** [comment]
Would be nice to have a benchmark using this piece of code to check everything is fine.
