### ISSUE TITLE
In the anomaly detection function, aggregate anomalies in chunks.

### ISSUE THREAD

**Issue by cloderic** [craft-ai/craft-ai-kit-energy#17]
# Objective #

- More directly usable result for the anomaly detection function.

# Definition of Done #

- Results of the anomaly detection function are aggregated depending on the triggered rules. i.e. when an anomaly is detected, as long as the applied decision rules doesn't change, fold the following anomalies with it.

**Comment by alexisfontaine** [comment]
We could also expose a parameter to set the threshold duration between two anomalies we want to aggregate. Should this be useful...

**Comment by cloderic** [comment]
Chekck the status on this one

**Comment by cloderic** [comment]
@rmdh & @alexisfontaine seems it doesn't work as described, is it normal ?

**Comment by rmdh** [comment]
I'm not sure this is justified. It would help with the specific task of indexing anomalies by tree leaf (and reduce the memory size of the output), but at the cost of added complexity for the user (more complex structure than an array of records, which is already used often in the kit).

I could see this task being useful though. A compromise could be to make this optional, or doable through an additional function.
